import { lazy, Suspense } from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { AuthProvider } from './contexts/AuthContext.jsx';
import AppErrorBoundary from './components/system/AppErrorBoundary';
import RouteFallback from './components/system/RouteFallback';
import NotFound from './components/system/NotFound';
import ProtectedRoute from './components/ProtectedRoute';
import MainLayout from './layouts/MainLayout';
import './styles/systemStates.css';
import './styles/responsiveSystem.css';
import './styles/compactSystem.css';

const Dashboard=lazy(()=>import('./pages/Dashboard'));const Clientes=lazy(()=>import('./pages/Clientes'));const CRM=lazy(()=>import('./pages/CRM'));const Trabalhos=lazy(()=>import('./pages/Trabalhos'));const Agenda=lazy(()=>import('./pages/Agenda'));const Financeiro=lazy(()=>import('./pages/Financeiro'));const Perfil=lazy(()=>import('./pages/Perfil'));const Equipamentos=lazy(()=>import('./pages/Equipamentos'));const Relatorios=lazy(()=>import('./pages/Relatorios'));const Precificacao=lazy(()=>import('./pages/Precificacao'));const Login=lazy(()=>import('./pages/Login'));const Configuracoes=lazy(()=>import('./pages/Configuracoes'));const ModelosPropostas=lazy(()=>import('./pages/Configuracoes/ModelosPropostas'));const Documentos=lazy(()=>import('./pages/Documentos'));const ProposalEditor=lazy(()=>import('./features/proposals/editor/ProposalEditor'));const ProposalTemplateEditor=lazy(()=>import('./features/documents/editor/ProposalTemplateEditor'));const ModelosContratos=lazy(()=>import('./pages/Configuracoes/ModelosContratos'));const ContractTemplateEditor=lazy(()=>import('./features/documents/editor/ContractTemplateEditor'));const AreaCliente=lazy(()=>import('./pages/AreaCliente'));const PortalCliente=lazy(()=>import('./pages/PortalCliente'));const BibliotecaArquivos=lazy(()=>import('./pages/BibliotecaArquivos'));const Galerias=lazy(()=>import('./pages/Galerias'));const GaleriaPublica=lazy(()=>import('./pages/GaleriaPublica'));const GaleriaPreview=lazy(()=>import('./pages/GaleriaPreview'));const MigracaoDados=lazy(()=>import('./pages/MigracaoDados'));const GoogleOAuthCallback=lazy(()=>import('./pages/GoogleOAuthCallback'));

function AppRoutes(){return <Suspense fallback={<RouteFallback/>}><Routes><Route path="/login" element={<Login/>}/><Route path="/recuperar-senha" element={<Login/>}/><Route path="/portal/:accessToken" element={<PortalCliente/>}/><Route path="/galeria/:accessToken" element={<GaleriaPublica/>}/><Route path="/oauth/google/callback" element={<GoogleOAuthCallback/>}/><Route path="/oauth/google/callback/*" element={<GoogleOAuthCallback/>}/><Route path="/" element={<ProtectedRoute><MainLayout/></ProtectedRoute>}><Route index element={<Dashboard/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="clientes" element={<Clientes/>}/><Route path="crm" element={<CRM/>}/><Route path="trabalhos" element={<Trabalhos/>}/><Route path="projetos" element={<Trabalhos/>}/><Route path="agenda" element={<Agenda/>}/><Route path="financas" element={<Financeiro/>}/><Route path="financeiro" element={<Financeiro/>}/><Route path="precificacao" element={<Precificacao/>}/><Route path="perfil" element={<Perfil/>}/><Route path="configuracoes" element={<Configuracoes/>}/><Route path="configuracoes/migracao-dados" element={<MigracaoDados/>}/><Route path="configuracoes/modelos-propostas" element={<ModelosPropostas/>}/><Route path="configuracoes/modelos-propostas/:templateId" element={<ProposalTemplateEditor/>}/><Route path="configuracoes/modelos-contratos" element={<ModelosContratos/>}/><Route path="configuracoes/modelos-contratos/:templateId" element={<ContractTemplateEditor/>}/><Route path="documentos" element={<Documentos/>}/><Route path="propostas/editor" element={<ProposalEditor/>}/><Route path="equipamentos" element={<Equipamentos/>}/><Route path="relatorios" element={<Relatorios/>}/><Route path="area-cliente" element={<AreaCliente/>}/><Route path="biblioteca" element={<BibliotecaArquivos/>}/><Route path="galerias" element={<Galerias/>}/><Route path="galerias/:galleryId" element={<Galerias/>}/><Route path="galerias/:galleryId/preview" element={<GaleriaPreview/>}/><Route path="*" element={<NotFound/>}/></Route><Route path="*" element={<NotFound/>}/></Routes></Suspense>}
function App(){return <AppErrorBoundary><BrowserRouter><AuthProvider><AppRoutes/></AuthProvider></BrowserRouter></AppErrorBoundary>}
export default App;
