/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect,useState } from 'react';
import { Copy,FilePlus2,MoreVertical,Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { listTemplates,saveTemplate,deleteTemplate } from '../../features/documents/storage/documentStorageAdapter';
import { cloneTemplateVersion } from '../../features/documents/services/templateVersionManager';
import { createId } from '../../features/documents/utils/documentIds';
import { CONTRACT_MODELS } from '../../data/contractModels';
import './ModelosContratos.css';

const fields=['client.name','client.cpf','client.rg','client.email','client.phone','client.address','work.type','work.date','work.time','work.location','package.name','package.services','pricing.total','pricing.deposit','pricing.installments','pricing.paymentConditions','studio.name','studio.cnpj','studio.address','studio.email','studio.phone','signature.client','signature.studio','signature.witness1','signature.witness2'];
const createPages=(count)=>Array.from({length:count},(_,index)=>({id:createId('contract-page'),name:index===0?'Capa':`Página ${index+1}`,order:index,active:true,width:595.28,height:841.89,background:{type:'pdf',url:null,opacity:1},elements:index===0?fields.slice(0,6).map((key,fieldIndex)=>({id:createId('field'),type:'dynamicField',placeholderKey:key,x:55,y:180+fieldIndex*42,width:260,height:26,fontFamily:'Helvetica',fontSize:11,fontWeight:'400',color:'#222222',align:'left',lineHeight:1.2,letterSpacing:0,opacity:1,hideIfEmpty:true,locked:false,visible:true})):[],metadata:{fixedLegalContent:true}}));

export default function ModelosContratos(){const navigate=useNavigate();const[templates,setTemplates]=useState([]);const[loading,setLoading]=useState(true);const refresh=async()=>{let items=await listTemplates({documentType:'contract'});if(!items.length){items=await Promise.all(CONTRACT_MODELS.map((model)=>saveTemplate({id:model.id,baseTemplateId:model.id,documentType:'contract',name:model.name,slug:model.id,category:model.type,version:1,status:'published',isPublished:true,isLatest:true,pages:createPages(model.pages),metadata:{originalPdf:model.sourceUrl,originalPageCount:model.pages,variableFields:fields,versionPublished:1,createdAt:new Date().toISOString()}})))}setTemplates(items);setLoading(false)};useEffect(()=>{void refresh()},[]);const createNew=async()=>{const saved=await saveTemplate({documentType:'contract',name:'Novo modelo de contrato',slug:`contrato-${Date.now()}`,category:'outro',version:1,status:'draft',pages:createPages(1),metadata:{variableFields:fields}});navigate(`/configuracoes/modelos-contratos/${saved.id}`)};return <section className="contract-model-list"><header><div><span>Configurações</span><h1>Modelos de Contratos</h1><p>Gerencie páginas, campos variáveis e versões publicadas.</p></div><button onClick={createNew}><FilePlus2/>Novo modelo de contrato</button></header>{loading?<p>Carregando modelos...</p>:<div className="contract-model-grid">{templates.filter((item)=>item.isLatest!==false).map((template)=><article key={template.id}><div className="contract-model-cover"><strong>{template.category}</strong><span>{template.pages.length} páginas</span></div><h2>{template.name}</h2><div className="contract-model-meta"><span>v{template.version}</span><span className={template.isPublished?'published':'draft'}>{template.isPublished?'Publicado':'Rascunho'}</span></div><footer><button onClick={()=>navigate(`/configuracoes/modelos-contratos/${template.id}`)}>Editar modelo</button><details><summary aria-label="Mais ações"><MoreVertical/></summary><div><button onClick={async()=>{await cloneTemplateVersion(template);await refresh()}}><Copy/>Duplicar</button><button onClick={async()=>{if(window.confirm('Excluir este modelo?')){await deleteTemplate(template.id);await refresh()}}}><Trash2/>Excluir</button></div></details></footer></article>)}</div>}</section>}
