import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Download, FileCheck2, X } from 'lucide-react';
import { CONTRACT_MODELS, suggestContractModel } from '../data/contractModels';
import { downloadPdf, generateContractPdf } from '../utils/contractPdf';
import './ContractWizard.css';

const steps=['Modelo','Cliente','Evento','Pacote','Pagamento','Específicos','Assinaturas','Revisão','PDF'];
const labels={noivos:'Nome dos noivos',cerimonia:'Cerimônia',recepcao:'Recepção',makingOf:'Making of',preWedding:'Pré-wedding',cobertura:'Cobertura',equipe:'Equipe',fotosEssenciais:'Fotos essenciais',cronograma:'Cronograma',cerimonial:'Cerimonial',deslocamento:'Deslocamento',hospedagem:'Hospedagem',alimentacao:'Alimentação',instituicao:'Instituição',curso:'Curso',turma:'Turma',representante:'Representante',alunos:'Alunos participantes',ensaio:'Ensaio',colacao:'Colação',duracao:'Duração',horaExtra:'Hora extra',fotosPorAluno:'Fotos por aluno',eventoColetivo:'Evento coletivo',tipoEnsaio:'Tipo de ensaio',participantes:'Participantes',quantidadeFotos:'Quantidade de fotos',fotosExtras:'Fotos extras',local:'Local',reagendamento:'Reagendamento',acompanhantes:'Acompanhantes extras',albumImpressos:'Álbum ou impressos'};

export default function ContractWizard({proposal,client,project,studio,onClose,onSave,initialModelId}){
  const suggested=useMemo(()=>suggestContractModel(proposal.service||project?.tipoServico),[project?.tipoServico,proposal.service]);
  const [step,setStep]=useState(initialModelId ? 1 : 0);const[modelId,setModelId]=useState(initialModelId || suggested.id);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  const model=CONTRACT_MODELS.find((item)=>item.id===modelId)||suggested;
  const [data,setData]=useState({clientName:client?.nome||proposal.clientName||'',clientDocument:client?.cpf||client?.cnpj||'',clientRg:client?.rg||'',clientEmail:client?.email||'',clientPhone:client?.telefone||client?.whatsapp||'',clientAddress:client?.endereco||[client?.cidade,client?.estado,client?.cep].filter(Boolean).join(', '),service:proposal.service||project?.tipoServico||'',eventDate:project?.data||'',startTime:project?.horario||'',endTime:project?.horarioFinal||'',location:project?.local||'',packageName:proposal.packageName||'',services:proposal.services||'',total:String(proposal.total||project?.valorContratado||''),deposit:String(proposal.deposit||''),balance:String(proposal.balance||''),paymentMethod:proposal.paymentMethod||'',installments:String(proposal.installments||''),dueDates:proposal.dueDates||'',studioName:studio.name,studioDocument:studio.document,studioPix:studio.pix||'',signatureCity:'',signatureDate:new Date().toISOString().slice(0,10),studioSignature:studio.signature||'',clientSignature:'',signatureStatus:'pendente',specific:{}});
  const update=(key,value)=>setData((current)=>({...current,[key]:value}));
  const finish=async()=>{setSaving(true);setError('');try{const generated=await generateContractPdf({model,contract:data});await onSave({model,data,generated});downloadPdf(generated.bytes,generated.fileName)}catch(e){setError(e instanceof Error?e.message:'Falha ao gerar contrato.')}finally{setSaving(false)}};
  return <div className="contract-overlay"><section className="contract-wizard"><header><div><span>Assistente de contrato</span><h2>{model.name}</h2></div><button onClick={onClose} aria-label="Fechar"><X/></button></header><ol className="contract-progress">{steps.map((label,index)=><li key={label} className={index===step?'active':index<step?'done':''}><span>{index+1}</span><small>{label}</small></li>)}</ol><main>
    {step===0&&<div className="contract-models">{CONTRACT_MODELS.map((item)=><button key={item.id} className={modelId===item.id?'selected':''} onClick={()=>setModelId(item.id)}><div className="contract-cover"><FileCheck2/></div><strong>{item.name}</strong><span>Versão {item.version} · {item.pages} páginas</span><span>{item.hasAttachments?'Inclui anexos':'Sem anexos adicionais'}</span></button>)}</div>}
    {step===1&&<Fields data={data} update={update} fields={[['clientName','Nome completo'],['clientDocument','CPF/CNPJ'],['clientRg','RG'],['clientEmail','E-mail'],['clientPhone','Telefone'],['clientAddress','Endereço completo']]}/>} 
    {step===2&&<Fields data={data} update={update} fields={[['service','Tipo de serviço'],['eventDate','Data do evento','date'],['startTime','Horário inicial','time'],['endTime','Horário final','time'],['location','Local'],['eventNotes','Observações']]}/>} 
    {step===3&&<Fields data={data} update={update} fields={[['packageName','Pacote aprovado'],['services','Serviços, adicionais e entregas'],['team','Equipe'],['duration','Duração']]}/>} 
    {step===4&&<Fields data={data} update={update} fields={[['total','Valor total'],['deposit','Entrada'],['balance','Saldo restante'],['paymentMethod','Forma de pagamento'],['installments','Quantidade de parcelas'],['dueDates','Datas de vencimento']]}/>} 
    {step===5&&<div className="contract-fields">{model.specificFields.map((key)=><label key={key}><span>{labels[key]||key}</span><textarea value={data.specific[key]||''} onChange={(e)=>setData((current)=>({...current,specific:{...current.specific,[key]:e.target.value}}))}/></label>)}</div>}
    {step===6&&<Fields data={data} update={update} fields={[['signatureCity','Local da assinatura'],['signatureDate','Data da assinatura','date'],['studioSignature','Assinatura cadastrada do estúdio'],['clientSignature','Assinatura manual do cliente'],['signatureStatus','Status da assinatura']]}/>} 
    {step===7&&<div className="contract-review"><h3>Revisão dos campos variáveis</h3>{Object.entries(data).filter(([,v])=>typeof v!=='object'&&v).map(([key,value])=><div key={key}><span>{key}</span><strong>{value}</strong></div>)}<p>O texto jurídico original não é editável e será preservado integralmente no PDF.</p></div>}
    {step===8&&<div className="contract-pdf-step"><iframe title="Pré-visualização do contrato original" src={`${model.sourceUrl}#toolbar=0&navpanes=0`}/><p>O PDF final preserva as {model.pages} páginas originais e inclui a ficha dos campos variáveis.</p>{error&&<div className="contract-error">{error}</div>}<button className="contract-generate" disabled={saving} onClick={finish}><Download/>{saving?'Gerando PDF...':'Gerar e baixar PDF'}</button></div>}
  </main><footer><button disabled={step===0} onClick={()=>setStep((s)=>s-1)}><ChevronLeft/>Voltar</button>{step<8&&<button className="next" onClick={()=>setStep((s)=>s+1)}>Avançar<ChevronRight/></button>}</footer></section></div>;
}
function Fields({data,update,fields}){return <div className="contract-fields">{fields.map(([key,label,type='text'])=><label key={key}><span>{label}</span><input type={type} value={data[key]||''} onChange={(e)=>update(key,e.target.value)}/></label>)}</div>}
