const PRE_EVENT = ['Contrato assinado','Entrada paga','Dados do cliente conferidos','Local confirmado','Data confirmada','Horário confirmado','Cronograma confirmado','Contatos importantes salvos','Equipe confirmada','Funções da equipe definidas','Transporte organizado','Rota conferida','Hospedagem organizada, quando necessária','Alimentação organizada, quando necessária','Previsão do tempo conferida, quando aplicável','Câmeras separadas','Lentes separadas','Flashes separados','Iluminação separada','Tripés separados','Gimbal separado','Drone separado, quando necessário','Microfones separados','Gravadores separados','Cabos separados','Carregadores separados','Baterias carregadas','Baterias extras separadas','Cartões formatados','Cartões extras separados','Equipamentos testados','Documentos separados','Autorizações conferidas','Roteiro de captação conferido','Referências visuais conferidas','Endereço enviado para a equipe','Horário de saída definido','Cliente contatado antes do evento'];
const SECURITY = ['Cartões conferidos','Backup principal realizado','Backup secundário realizado','Arquivos copiados e conferidos','Arquivos organizados em pastas','Cartões liberados somente após confirmação dos backups'];
const PHOTO = ['Seleção das fotos','Sincronização das câmeras','Tratamento inicial','Edição das fotos','Revisão das fotos','Exportação das fotos','Galeria criada','Galeria revisada'];
const VIDEO = ['Arquivos de vídeo organizados','Arquivos de áudio organizados','Sincronização de áudio','Seleção dos takes','Montagem inicial','Edição do vídeo','Correção de cor','Tratamento de áudio','Revisão do vídeo','Exportação do vídeo'];
const DELIVERY = ['Arquivos finais conferidos','Material entregue','Cliente avisado','Data real de entrega registrada','Confirmação de recebimento','Avaliação solicitada','Trabalho finalizado','Arquivos arquivados'];
export const CHECKLIST_TEMPLATES = Object.freeze({ pre_evento: Object.freeze(PRE_EVENT), seguranca: Object.freeze(SECURITY), fotografia: Object.freeze(PHOTO), filmagem: Object.freeze(VIDEO), entrega: Object.freeze(DELIVERY) });
const id = (prefix = 'check') => `${prefix}-${globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`}`;
const serviceKey = (value) => String(value || '').toLocaleLowerCase('pt-BR');
export const createChecklist = (serviceType = '') => {
  const service = serviceKey(serviceType); const includePhoto = !service || service.includes('foto'); const includeVideo = service.includes('film');
  const titles = [...PRE_EVENT.map((titulo) => ['pre_evento', titulo]), ...SECURITY.map((titulo) => ['pos_evento', titulo]), ...(includePhoto ? PHOTO.map((titulo) => ['pos_evento', titulo]) : []), ...(includeVideo ? VIDEO.map((titulo) => ['pos_evento', titulo]) : []), ...DELIVERY.map((titulo) => ['pos_evento', titulo])];
  const now = new Date().toISOString();
  return { itens: titles.map(([categoria, titulo], ordem) => ({ id: id(), titulo, concluido: false, categoria, personalizado: false, ordem, criadoEm: now, concluidoEm: '', observacao: '' })), atualizadoEm: now };
};
const legacyId = (item, index) => `legacy-check-${item.categoria || 'personalizado'}-${Number.isFinite(Number(item.ordem)) ? Number(item.ordem) : index}-${String(item.titulo || item.title || 'item').toLocaleLowerCase('pt-BR').replace(/[^a-z0-9]+/g, '-').slice(0, 32)}`;
export const normalizeChecklist = (value) => {
  const source = Array.isArray(value) ? value : (Array.isArray(value?.itens) ? value.itens : []);
  const itens = source.map((item, index) => ({ ...item, id: item.id || legacyId(item, index), titulo: item.titulo || item.title || '', concluido: Boolean(item.concluido ?? item.done), categoria: item.categoria || 'personalizado', personalizado: Boolean(item.personalizado), ordem: Number.isFinite(Number(item.ordem)) ? Number(item.ordem) : index, criadoEm: item.criadoEm || '', concluidoEm: item.concluidoEm || '', observacao: item.observacao || '' })).sort((a,b) => a.ordem-b.ordem);
  return { itens, atualizadoEm: value?.atualizadoEm || '' };
};
export const checklistProgress = (value, category) => { const items = normalizeChecklist(value).itens.filter((item) => !category || item.categoria === category); const completed = items.filter((item) => item.concluido).length; return { total: items.length, completed, pending: items.length-completed, percentage: items.length ? Math.round(completed/items.length*100) : 0 }; };
export const toggleChecklistItem = (value, itemId, completed, now = new Date().toISOString()) => { const checklist = normalizeChecklist(value); return { ...checklist, itens: checklist.itens.map((item) => item.id === itemId ? { ...item, concluido: completed, concluidoEm: completed ? now : '' } : item), atualizadoEm: now }; };
export const upsertCustomItem = (value, draft) => { const checklist = normalizeChecklist(value); const titulo = String(draft.titulo || '').trim().replace(/\s+/g,' '); if (!titulo) throw new Error('Informe o título do item.'); const categoria = draft.categoria || 'personalizado'; if (checklist.itens.some((item) => item.id !== draft.id && item.categoria === categoria && serviceKey(item.titulo) === serviceKey(titulo))) throw new Error('Já existe um item com este título nesta categoria.'); const existing = checklist.itens.find((item) => item.id === draft.id); const item = { ...(existing || {}), ...draft, id: existing?.id || id('custom'), titulo, categoria, personalizado: existing ? existing.personalizado : true, concluido: Boolean(existing?.concluido ?? draft.concluido), ordem: existing?.ordem ?? checklist.itens.length, criadoEm: existing?.criadoEm || new Date().toISOString() }; return { itens: existing ? checklist.itens.map((entry) => entry.id === item.id ? item : entry) : [...checklist.itens, item], atualizadoEm: new Date().toISOString() }; };
export const removeChecklistItem = (value, itemId) => { const checklist = normalizeChecklist(value); return { ...checklist, itens: checklist.itens.filter((item) => item.id !== itemId), atualizadoEm: new Date().toISOString() }; };
